# Generated by Django 5.1 on 2024-11-20 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('mail', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('born', models.DateField(null=True)),
                ('register', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
